// Maps each city in the app's canonical city list (see
// components/ui/CitySelect.jsx) to its real Indian state. This app's data
// model treats city -> state as many-to-one, so a selected city fully
// determines its state — no separate state picker is needed.
const CITY_STATE_MAP = {
  'Agra': 'Uttar Pradesh',
  'Ahmedabad': 'Gujarat',
  'Ajmer': 'Rajasthan',
  'Aligarh': 'Uttar Pradesh',
  'Allahabad': 'Uttar Pradesh',
  'Amravati': 'Maharashtra',
  'Amritsar': 'Punjab',
  'Aurangabad': 'Maharashtra',
  'Bangalore': 'Karnataka',
  'Bareilly': 'Uttar Pradesh',
  'Bhopal': 'Madhya Pradesh',
  'Bhubaneswar': 'Odisha',
  'Chandigarh': 'Chandigarh',
  'Chennai': 'Tamil Nadu',
  'Coimbatore': 'Tamil Nadu',
  'Dehradun': 'Uttarakhand',
  'Delhi NCR': 'Delhi',
  'Faridabad': 'Haryana',
  'Ghaziabad': 'Uttar Pradesh',
  'Goa': 'Goa',
  'Gurugram': 'Haryana',
  'Guwahati': 'Assam',
  'Gwalior': 'Madhya Pradesh',
  'Howrah': 'West Bengal',
  'Hubli': 'Karnataka',
  'Hyderabad': 'Telangana',
  'Indore': 'Madhya Pradesh',
  'Jabalpur': 'Madhya Pradesh',
  'Jaipur': 'Rajasthan',
  'Jalandhar': 'Punjab',
  'Jammu': 'Jammu and Kashmir',
  'Jodhpur': 'Rajasthan',
  'Kanpur': 'Uttar Pradesh',
  'Kochi': 'Kerala',
  'Kolkata': 'West Bengal',
  'Kozhikode': 'Kerala',
  'Lucknow': 'Uttar Pradesh',
  'Ludhiana': 'Punjab',
  'Madurai': 'Tamil Nadu',
  'Mangalore': 'Karnataka',
  'Meerut': 'Uttar Pradesh',
  'Mumbai': 'Maharashtra',
  'Mysore': 'Karnataka',
  'Nagpur': 'Maharashtra',
  'Nashik': 'Maharashtra',
  'Navi Mumbai': 'Maharashtra',
  'Noida': 'Uttar Pradesh',
  'Patna': 'Bihar',
  'Pune': 'Maharashtra',
  'Raipur': 'Chhattisgarh',
  'Rajkot': 'Gujarat',
  'Ranchi': 'Jharkhand',
  'Srinagar': 'Jammu and Kashmir',
  'Surat': 'Gujarat',
  'Thane': 'Maharashtra',
  'Thiruvananthapuram': 'Kerala',
  'Tiruchirappalli': 'Tamil Nadu',
  'Udaipur': 'Rajasthan',
  'Vadodara': 'Gujarat',
  'Varanasi': 'Uttar Pradesh',
  'Vijayawada': 'Andhra Pradesh',
  'Visakhapatnam': 'Andhra Pradesh',
};

function getStateForCity(city) {
  return CITY_STATE_MAP[city] || '';
}

module.exports = { CITY_STATE_MAP, getStateForCity };
